### PR TITLE
Update to new design

### PR DESCRIPTION
**Pull request by psjnek**
I redesigned the FreeOTP website to look more modern.

Screenshot:
image

Let me know what you think about it...

### CODE REVIEW

**Comment by psjnek** [comment]
@justin-stephenson 

I am also redesigning the QR Code Generator. This is what is currently looks like.

Screenshot:
image

What do you think?

**Comment by psjnek** [comment]
@justin-stephenson 
Could you maybe provide the updated logo and some modern screenshots of the app please?

**Comment by psjnek** [comment]
@justin-stephenson 
Should I change the error.svg to this?

Screenshot:
image

**Comment by justin-stephenson** [comment]
> @justin-stephenson
> 
> I am also redesigning the QR Code Generator. This is what is currently looks like.
> 
> Screenshot: image
> 
> What do you think?

Looks good, could you align the input boxes and labels similar to https://stefansundin.github.io/2fa-qr/ ?

**Comment by justin-stephenson** [comment]
> @justin-stephenson Should I change the error.svg to this?
> 
> Screenshot: image

Okay with me.

**Comment by justin-stephenson** [comment]
Don't worry about the commit history, I will propose to squash it into a single commit before merging

**Pull request closed without merging**
